name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install
          npm run-script build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_PUBLIC_KEY: ${{ secrets.VITE_PUBLIC_KEY }}
          VITE_PRIVATE_KEY: ${{ secrets.VITE_PRIVATE_KEY }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CNAME:
